### PR TITLE
Pull path to bash from env

### PR DESCRIPTION
**Pull request by qbit**
On OpenBSD bash is installed in /usr/local/bin

### CODE REVIEW

**Comment by oubiwann** [comment]
Thanks!

**Comment by qbit** [comment]
Looks like this was undone some how. Any chance we can get it added back?

**Comment by oubiwann** [comment]
Oh, dear ... let me look into this and see what happened :-/

**Comment by oubiwann** [comment]
Oh, I see why -- I didn't catch this when I looked at it the first time: you changed the lfetool script ... which is generated. You need to change the template from which it is generated: `plugins/lfetool/templates/lfetool.tmpl`.

Which reminds me -- I need to update the script so that this is explicitly stated in the script itself :-/

**Comment by oubiwann** [comment]
Added warning in 00112ff.

**Pull request merged**
